# Site Build Settings

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

# SEO meta tags
title:		           'NatsuCamellia'
description:	       "When camellia blooms in summer."
author:              'NatsuCamellia'